// TEN PLIK ZAWIERA ELEMENTY SKŁADOWE, KTÓRE BĘDĄ LOSOWANE PRZEZ MASZYNĘ LOSUJĄCĄ

var dictPrefix = [ // eslint-disable-line no-unused-vars
        "A", "Ab", "Abi", "Acco", "Ad", "Ada", "Agro", "Akwa", "Alko", "All", "Amber", "Anio", "Anno", "Anty", "Archi", "Argo", "Art", "Astro", "Audio", "Auto", "Baj", "Bar", "Bell", "Bet", "Beton", "Bi", "Bial", "Biuro", "Bitu", "Blach", "Bruk", "Bud", "Budi", "Budo", "Can", "Car", "Center", "Centro", "Ceram", "Chem", "Chemo", "Chl", "Com", "Comp", "Cosmo", "Cyber", "Cyklo", "Czech", "Dach", "Dan", "Dar", "Deco", "Deli", "Delta", "Dom", "Drew", "Drog", "Druk", "Drut", "Eco", "Edi", "Eko", "Eks", "El", "Elektro", "Energo", "Ergo", "Euro", "Ex", "Farm", "Fem", "Firma", "For", "Form", "Foto", "Frukto", "Gastro", "Gaz", "Gazo", "Geo", "Giga", "Gold", "Graf", "Greg", "Gum", "Handlo", "Hali", "Herba", "Hurt", "Hydro", "Info", "Inst", "Instal", "In", "Inter", "Inwest", "Izo", "Janusz", "Jadło", "Jar", "Jurek", "Kabel", "King", "Kabel", "Kablo", "Klima", "Kom", "Komp", "Krys", "Ksero", "Kwiat", "Lech", "Lider", "Łuk", "Mak", "Makro", "Mar", "Mat", "Mart", "Max", "Meblo", "Med", "Medi", "Mega", "Metal", "Mięs", "Mikro", "Mirko", "Miro", "Moto", "Multi", "Nafto", "Natur", "Net", "Nova", "Nowa", "Okno", "Opon", "Petro", "Peklo", "Plast", "Plas", "Płyt", "Pol", "Polo", "Poli", "Pre", "Pro", "Pul", "Rafa", "Remo", "Remont", "Sebo", "Siat", "Sław", "Sol", "Spaw", "Stal", "Stol", "Super", "Szaf", "Szkło", "Szwagro", "Tech", "Techno", "Tele", "Termo", "Tex", "Tom", "Top", "Trans", "Uni", "Wam", "Węglo", "Wielo", "Wol", "Zam", "Zby", "Zbych", "Złom", "Zoo"
    ],
    dictInfix = [ // eslint-disable-line no-unused-vars
        "", "a", "ab", "al", "bor", "bos", "but", "chem", "col", "czar", "dup", "e", "eco", "eko", "es", "euro", "gips", "gum", "i", "int", "inw", "farm", "fil", "filc", "ko", "kom", "kosm", "la", "las", "li", "mar", "me", "med", "mot", "my", "o", "per", "plast", "pol", "serw", "tech", "ti", "to", "ty", "u", "wit", "y"
    ],
    dictSufix = [ // eslint-disable-line no-unused-vars
        "ak", "aks", "am", "an", "art", "arz", "ax", "bud", "but", "bur", "ch", "dex", "deks", "dent", "eks", "ek", "em", "en", "er", "erz", "ex", "farm", "gips", "graf", "gum", "imo", "in", "jan", "kom", "lex", "log", "mag", "mark", "mech", "mer", "met", "mex", "mir", "miks", "mix", "model", "mont", "o", "onik", "pasz", "pol", "rom", "rol", "rok", "sport", "studio", "sz", "te", "tek", "tex", "tech", "ten", "trans", "ux", "uks", "weks", "zer"
    ];
